### ISSUE TITLE
Release v0.0.2 to GitHub

### ISSUE THREAD

**Issue by almereyda** [sebastienrousseau/open-sans#3]
The website and last commits speak of an existing v0.0.2, also offered for download.

Since a v0.0.1 is already present on GitHub, it could be convenient to also find the v0.0.2 assetts alongside the repository.

**Comment by sebastienrousseau** [comment]
@almereyda Thanks, this has been resolved.

**Comment by almereyda** [comment]
Welcome, and thanks in return.
